import { UnparsedExam } from '../types'

/* eslint-disable prettier/prettier */
export const sampleExam: UnparsedExam = {
	name: 'Example Test',
	exercises: [
		'I {?see=saw} your sister yesterday.',
		'When we were in Africa, it {?rain=rained} a lot.',
		'Last Sunday I {?visit=visited} my grandparents.',
		'My brother {?wear=wore} jeans when he got married.',
		'They {?have=had} an accident last night.',
		'I was surprised when he {?walk=walked} into the room.',
		'She {?play=played} a lot of football when she was young.',
		'I {?fall=fell} asleep while I was watching TV.',
		'He {?burn=burned} his hand when he was cooking dinner.',
		'Two years ago, they {?move=moved} to Rotterdam.',
		'In medieval times, people {?not use=did not use} highly developed techniques.',
		'Paul and Lucas {?meet=met} once a week when they were young, but not anymore.',
		'When my dad was a little boy, he {?not have=did not have} much money to spend.',
		'Last August we {?not go=did not go} abroad, but we stayed in the Netherlands.',
		'When my mother was a little girl, she {?own=owned} her own horse.',
		'{?you see=Did you see} that movie on TV last night?',
		'You {?be=were} much smaller when I last saw you.',
		'When I was 4 years old I {?fall=fell} down the stairs twice in one week.',
		'Jacky and Chris {?not go=did not go} to Hawaii last year, but they {?go=went} to Germany.',
		'Somebody {?find=found} my father’s wallet two hours ago.',
		'The angry man {?leave=left} the restaurant five minutes ago.',
		'Last night I {?not fall=did not fall} asleep very quickly and I {?wake=woke} up very late.',
		'When my father was a little boy he often {?play=played} outside in the forest.',
		'Yesterday, Robin said that he {?hear=heard} that before.',
		'When we were in that restaurant last Saturday I {?not order=did not order} any shrimp because I am allergic.',
		'When my grandfather was a child, he {?live=lived} on a farm.',
		'The first time we {?go=went} to the US was in 2003.',
		'She {?break=broke} her leg in August.',
		'A few weeks ago, my uncle {?not sell=did not sell} any cars.',
		'Yesterday, he {?not bring=did not bring} his books to class.',
		'Last week, he {?forget=forgot} to bring his PE clothes.',
		'Last night, Sam {?look=looked} after his little brother.',
		'Mitchell {?live=lived} in Moscow when he was young and therefore can speak Russian.',
		'My parents {?give=gave} me a Nintendo Switch for my last birthday.',
		'{?you see=Did you see} the last episode of Friends last night?',
		'She {?write=wrote} me an interesting email last night.',
		'My little brother {?wake=woke} me up very early this morning because of a nightmare.',
		'I {?not get=did not get} up early this morning.',
		'We {?move=moved} to the city three years ago.',
		'We {?have=had} the chance to visit many museums in Paris last holiday.',
		'Harry {?not come=did not come} to school this morning because he was ill.',
		'Last summer Ruben {?sail=sailed} across the North Sea.',
		'Where {?you spend=did you spend} your holiday last August?',
		'During English class today, we {?have=had} a lot of fun.',
		'He {?start=started} wearing glasses when he was 11 years old.',
		'The train {?stop=stopped} at every station this morning.',
		'All my relatives {?send=sent} me birthday cards last week.',
		'Thomas {?go=went} to school by bike yesterday.',
		'The famous pop group {?not play=did not play} at the concert last month.',
	],
}
