import { UnparsedExam } from '../types'

/* eslint-disable prettier/prettier */
export const sampleExam: UnparsedExam = {
	name: 'Example Test',
	exercises: [
		'I {?help=help} my sister with the dishes.',
		'George {?work=works} in Oxford.',
		'My mother and I {?like=like} to go shopping in the weekend.',
		'Linda {?try=tries} to do her homework.',
		'The dog {?do=does} tricks.',
		'They {?buy=buy} their clothes online.',
		'She {?wish=wishes} she was done with her assignment.',
		'We {?drink=drink} tea with our breakfast.',
		'We {?have=have} a dog.',
		'George {?not like=doesn’t like} dark chocolate.',
		'{?you do=Do you do} your homework every day?',
		'They {?walk=walk} to work every morning.',
		'I {?not help=don’t help} my parents with the household chores.',
		'{?John have=Does John have} any siblings?',
		'Charlie {?work=works} on a project with Alex.',
		'{?I be=Am I} late for work?',
		'We {?not watch=don’t watch} TV in the morning.',
		'Linda {?study=studies} English at Cambridge University.',
		'{?he go=Does he go} for a walk in the weekend?',
		'I usually {?dance=dance} in a competition on Saturday.',
		'You {?not enjoy=don’t enjoy} horror films',
		'She {?not cook=doesn’t cook} dinner, her girlfriend is a better cook.',
		'Sally never {?wash=washes} her car.',
		'The plane {?fly=flies} to Spain every week.',
		'We often {?visit=visit} our relatives.',
		'My brother {?love=loves} his dog.',
		'Celebrities {?have=have} to deal with the press.',
		'Every year, we {?go=go} to France in summer.',
		'Our dog {?love=loves} to chase tennis balls.',
		'He {?live=lives} in Eindhoven.',
		'He {?not play=doesn’t play} soccer anymore.',
		'{?you know=Do you know} her?',
		'She never {?pay=pays} her bills on time.',
		'My parents {?not enjoy=don’t enjoy} their retirement all that much.',
		'Where {?she live=does she live}?',
		'Why {?Dutch people cycle=Do Dutch people cycle} so much?',
		'My uncle {?not like=doesn’t like} opera.',
		'Normally, my friend and I {?meet=meet} once a week to watch a movie together.',
		'My teacher usually {?explain=explains} grammar really well.',
		'I {?not understand=don’t understand} this grammar topic.',
		'My little sister usually {?make=makes} her own breakfast.',
		'Sometimes my mother {?make=makes} breakfast for us all.',
		'He always {?fall=falls} asleep when we watch TV.',
		'That team usually {?lose=loses} when they get nervous.',
		'My friends always {?bring=brings} candy when we meet up.',
		'That guy always {?wear=wears} jeans.',
		'That dish {?smell=smells} absolutely wonderful!',
		'It normally {?rain=rains} a lot in England.',
		'I never {?read=read} the newspaper.',
		'My grandfather {?not know=doesn’t know} how to ride a bike anymore.',
		'They {?not have=don’t have} any dairy products because they are allergic to milk.',
		'They usually {?not watch=don’t watch} the news in the evening.',
		'{?your grandparents give=Do your grandparents give} you money every year?',
		'She always {?wear=wears} her favourite outfit on Wednesdays.',
		'My uncle {?sell=sells} cars for a living.',
		'Mick often {?forget=forgets} to bring his books to class.',
		'{?she often visit=Does she often visit} her grandparents?',
		'I always {?take=take} the train to school.',
	],
}
